<a href="https://colab.research.google.com/github/jpbeaud/dbscan/blob/main/client.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import time

def string_to_number(s):
  return int(''.join(str(ord(char)) for char in s))



chemin = "/content/sample_data/"
debut = time.time()
print("Début à", debut)



fichier_DH = pd.read_csv(chemin+"extrac_DH.csv", sep=",", dtype=str,skipinitialspace=True)

fichier_DH = fichier_DH.replace("", np.nan)
fichier_DH = fichier_DH.fillna(0)

fichier_DH = fichier_DH.astype(str)
col_ref = ['id_personne']
references_DH = fichier_DH[col_ref]



fichier_DH.sort_values(by='id_personne')

fichier_DH2 = fichier_DH
fichier_DH2 = fichier_DH2.drop('id_personne', axis='columns')

fichier_DH2= fichier_DH2.astype(str)
fichier_DH2 = fichier_DH2.map(string_to_number)



#fichier_DH.set_index('id_personne', inplace=True) # inplace=True --> on ne crée pas un nouveau DF




fichier_SIO = pd.read_csv(chemin+"extrac_SIO.csv", sep=",", dtype=str,skipinitialspace=True)
col_ref = ['client_reference']

references_SIO= fichier_SIO[col_ref]
ref_cli = references_SIO.to_numpy()

fichier_SIO = fichier_SIO.replace("", np.nan)
fichier_SIO = fichier_SIO.fillna(0)



fichier_SIO.sort_values(by='client_reference')
fichier_SIO = fichier_SIO.astype(str)
fichier_SIO = fichier_SIO.map(string_to_number)


fichier_SIO = fichier_SIO.drop('client_reference',axis='columns')
#print ("fichier SIO format :")
#print(fichier_SIO.head())
# X = fichier_DH.to_numpy()



Début à 1730895972.2819908
Estimated number of clusters DH: 4
Estimated number of noise points DH: 60721
fichier SIO après scaler :
[[ 0.99524004 -0.13624662  0.34734841  0.13574068  0.43858857  0.63492088
   0.63447928 -0.00316229]
 [ 1.03176323 -0.13624662  0.34734841  0.13574068  0.43858857  0.63492088
   0.63447928 -0.00316229]
 [ 1.03288129 -0.13624662  0.34734841  0.13574068  0.43858857 -1.13808606
  -1.13277895 -0.00316229]
 [ 0.99524004 -0.13624662  0.34734841  0.13574068  0.43858857 -1.13808606
  -1.13277895 -0.00316229]
 [ 0.92182096 -0.13624662  0.34734841  0.13574068  0.43858857  0.63492088
   0.63447928 -0.00316229]]
Estimated number of clusters SIO: 3
Estimated number of noise points SIO: 76484
____________Résumé____________
Données en écarts =  [ 0  0  0 ... -1  0  0]
[-1 -1 -1 ...  0 -1 -1]
[-1 -1 -1 ...  1 -1 -1]
Longueur dif =  100000


Ficher DB2 et SIO

In [11]:
# prompt: comment calculer le nombre d'enregistrements différents dans fichier_DH2

# Calculate the number of unique records in fichier_DH2
unique_records_count = len(fichier_DH2.drop_duplicates())

print(f"Number of unique records in fichier_DH2: {unique_records_count}")

# Calculate the number of unique records in fichier_SIO
unique_records_count = len(fichier_SIO.drop_duplicates())

print(f"Number of unique records in fichier_SIO: {unique_records_count}")

Number of unique records in fichier_DH2: 14725
Number of unique records in fichier_SIO: 17079


Appel à DBSCAN

In [15]:
X = fichier_DH2
#X.set_index('id_personne', inplace=True) # inplace=True --> on ne crée pas un nouveau DF

# print(X.dtype)
X = X.apply(pd.to_numeric)

import matplotlib.pyplot as plt
# pltcatter(X[:, 3], X[:, 4])


#plt.scatter(x="pcs" , y="cosop", c = 'r', data=X)
#plt.show()

from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler

# création du jeu de test

#X = StandardScaler().fit_transform(X)
#print ("fichier DH2 après scaler :")
#print(X[:5])

from sklearn import metrics
from sklearn.cluster import DBSCAN
from sklearn.cluster import OPTICS
min_groupe = 5
db = DBSCAN(eps=0.000000000000001,min_samples=min_groupe).fit(X)
labels_DH = db.labels_

n_clusters_ = len(set(labels_DH)) - (1 if -1 in labels_DH else 0)
n_noise_ = list(labels_DH).count(-1)

print("Estimated number of clusters DH: %d" % n_clusters_)
print("Estimated number of noise points DH: %d" % n_noise_)


Y = fichier_SIO


#Y = StandardScaler().fit_transform(Y)
#print ("fichier SIO après scaler :")
#print(Y[:5])


# Y = Y.apply(pd.to_numeric)
db2 = DBSCAN(eps=0.00000000000001, min_samples=min_groupe).fit(Y)
labels_SIO = db2.labels_



n_clusters_ = len(set(labels_SIO)) - (1 if -1 in labels_SIO else 0)
n_noise_ = list(labels_SIO).count(-1)

print("Estimated number of clusters SIO: %d" % n_clusters_)
print("Estimated number of noise points SIO: %d" % n_noise_)
print("____________Résumé____________")
difference = labels_DH - labels_SIO
print("Données en écarts = ", difference)
print(labels_DH)
print(labels_SIO)
n_DH = len(labels_DH)
n_SIO=len(labels_SIO)
n_dif = len(difference)
print("Longueur dif = ", n_dif)
fin = False
i=-1

nb_ko = 0

# Créer un tableau vide avec une dimension initiale
empty_array = np.empty((0, 3))  # Par exemple, un tableau vide avec 3 colonnes



Estimated number of clusters DH: 1855
Estimated number of noise points DH: 16678
Estimated number of clusters SIO: 1844
Estimated number of noise points SIO: 19101
____________Résumé____________
Données en écarts =  [  0   0   0 ... -10  12   0]
[  0  -1   1 ...   4 727  -1]
[  0  -1   1 ...  14 715  -1]
Longueur dif =  100000


On sélectionne les enregistrements qui ont 0 comme label

In [16]:
labels_DH_zero = [x for x in labels_DH if x ==0]
print("longueur DH label 0 =", len(labels_DH_zero))
labels_SIO_zero = [x for x in labels_SIO if x ==0]
print("longueur SIO label 0 =", len(labels_SIO_zero))


longueur DH label 0 = 203
longueur SIO label 0 = 190


In [18]:
# prompt: transform labels_DH into a dataframe

#print("DH.38=", X[38], "SIO.38=", Y[38])
#print("DH.0=", X[0], "SIO.0=", Y[0])

# Assuming 'labels_DH' is already defined from the previous code
labels_DH_df = pd.DataFrame({'labels_DH': labels_DH})
labels_SIO_df = pd.DataFrame({'labels_SIO': labels_SIO})

labels_DH_0 = labels_DH_df[labels_DH_df['labels_DH'] == 0]
print(labels_DH_0.head())
labels_SIO_0 = labels_SIO_df[labels_SIO_df['labels_SIO'] == 0]
print(labels_SIO_0.head())
print("______________________________________________________")
print(labels_DH[38], " SIO=", labels_SIO[38])
print("Référence SIO", references_SIO.iloc[38], ". Référence DH = ", references_DH.iloc[38])




    labels_DH
0           0
12          0
29          0
40          0
53          0
    labels_SIO
0            0
12           0
29           0
40           0
53           0
______________________________________________________
-1  SIO= -1
Référence SIO client_reference    0000005330
Name: 38, dtype: object . Référence DH =  id_personne    0000005330
Name: 38, dtype: object


Test A

In [ ]:
# Deux tableaux à une dimension
#array1 = np.array([1, 2, 3])
#array2 = np.array([4, 5, 6]) # Empiler verticalement
#result = np.vstack((array1, array2))
#print(result)
#print(array1.shape)

#print(result.shape)


liste = []
A = np.empty((0, 10000), dtype=int)

for i in range(10000):
  liste = []
  for j in range(10000):
    liste.append(labels_DH[i] -labels_DH[j])
  A = np.vstack([A, liste])


print(A)



KeyboardInterrupt: 

Fin

In [ ]:
RRR






while (i < n_dif - 1):
    i = i + 1
    if (difference[i] != 0):
        print("i=",i)
        print("différence enregistrement ", str(i), " DH=", labels_DH[i], "// SIO=",labels_SIO[i], "// ref=", ref_cli[i,:])
        #print("enr DH=", fichier_DH.loc[i,:])
        #print("enr SIO=",fichier_SIO.loc[i,:])
        nb_ko = nb_ko + 1
        X = np.delete(X,i,0)
        Y = np.delete(Y,i,0)
        ref_cli = np.delete(ref_cli,i,0)
        db = DBSCAN(eps=0.000000000000001,min_samples=min_groupe).fit(X)
        labels_DH = db.labels_
        db2 = DBSCAN(eps=0.00000000000001, min_samples=min_groupe).fit(Y)
        labels_SIO = db2.labels_
        difference = labels_DH - labels_SIO
        n_dif = n_dif - 1


lg = len(difference)
#nb_ano = 0
#for i in range(lg):
#    if difference[i] !=0:
#        nb_ano = nb_ano + 1
print("ANOMALIES = ", nb_ko)
#  3117773703

fin_exec = time.time()
temps = fin_exec - debut
print(f'Temps d\'exécution : {temps:.2}ms')